finetune_background: True
finetune_foreground: False
checkpoint_path: data/pretrained_nla_models/car-turn/checkpoint # path to the checkpoint file
maximum_number_of_frames: 70 # maximum number of frames to use in the video

screen_text: ["winter scene", "snow everywhere", "beautiful snow"] # texts, describing the edit layer
comp_text: ["winter countryside scene", "snowy countryside scene", "beautiful snow"] # texts, describing the full edited video
src_text: ["countryside", "countryside with trees", "countryside"] # texts, describing the input video

n_epochs: 3000 # number of epochs to train
