finetune_background: False
finetune_foreground: True
checkpoint_path: data/pretrained_nla_models/libby/checkpoint # path to the checkpoint file
maximum_number_of_frames: 49 # maximum number of frames to use in the video

screen_text: ["dog made out of diamonds"] # texts, describing the edit layer
comp_text: ["dog made out of diamonds"] # texts, describing the full edited video
src_text: ["dog"] # texts, describing the input video
